# Generated by Django 4.2.1 on 2023-05-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Autor', models.CharField(max_length=50)),
                ('Editorial', models.CharField(max_length=50)),
            ],
        ),
    ]
